# Generated by Django 4.1.5 on 2023-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='cook_time_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cook_time_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='meal',
            name='prep_time_hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='prep_time_minutes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='url',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
