# Generated by Django 4.1.5 on 2023-04-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_cook_time_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
