# Generated by Django 4.1.5 on 2023-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_ingredient',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='meal_ingredient',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
